import type { XmlFieldMeta, XmlTypeMeta } from "../meta-types.js";

// ---------------------------------------------------------------------------
// Options
// ---------------------------------------------------------------------------

export interface XmlSerializeOptions {
  /**
   * Override the root element name. Defaults to `meta.xmlName`.
   */
  rootElement?: string;
  /**
   * Indentation string, e.g. `"  "` or `"\t"`. When omitted the output is
   * compact (no extra whitespace between elements).
   */
  indent?: string;
  /**
   * XML namespace URI placed as `xmlns="..."` on the root element.
   */
  namespace?: string;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Serialize a plain JavaScript object to an XML string using the XmlTypeMeta
 * generated by xsd2zod.
 *
 * The meta graph produced by the generator is self-contained: every field that
 * references a named complex type has a `nestedMeta` property pointing to that
 * type's meta object. No external registry is required.
 *
 * @example
 * ```ts
 * import { objectToXml } from "xsd2zod";
 * import { PersonMeta } from "./generated.js";
 *
 * const xml = objectToXml({ name: "Alice", age: 30 }, PersonMeta, { indent: "  " });
 * ```
 */
export function objectToXml(
  value: unknown,
  meta: XmlTypeMeta,
  options: XmlSerializeOptions = {}
): string {
  const rootName = options.rootElement ?? meta.xmlName;
  const lines: string[] = [];
  serializeObject(value, meta, rootName, options, lines, 0);
  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Core serialization helpers
// ---------------------------------------------------------------------------

function serializeObject(
  value: unknown,
  meta: XmlTypeMeta,
  elementName: string,
  options: XmlSerializeOptions,
  out: string[],
  depth: number
): void {
  if (value === null || value === undefined) return;
  if (typeof value !== "object" || Array.isArray(value)) return;

  const obj = value as Record<string, unknown>;

  // Separate attribute fields from element / text fields
  const attrFields: XmlFieldMeta[] = [];
  const contentFields: XmlFieldMeta[] = [];

  for (const fm of Object.values(meta.fields)) {
    if (fm.kind === "attribute") attrFields.push(fm);
    else contentFields.push(fm);
  }

  // Build attribute string
  let attrStr = "";
  for (const fm of attrFields) {
    const jsName = findJsName(meta, fm);
    const raw = obj[jsName];
    if (raw === undefined || raw === null) continue;
    attrStr += ` ${fm.xmlName}="${escapeAttr(String(raw))}"`;
  }

  // Namespace on root element only — options.namespace overrides meta.namespace
  const ns = depth === 0 ? (options.namespace ?? meta.namespace) : undefined;
  if (ns) {
    attrStr += ` xmlns="${escapeAttr(ns)}"`;
  }

  // Sort content fields by order for sequence compositor; keep definition
  // order otherwise
  const sorted = [...contentFields].sort((a, b) => {
    if (a.order !== undefined && b.order !== undefined) return a.order - b.order;
    if (a.order !== undefined) return -1;
    if (b.order !== undefined) return 1;
    return 0;
  });

  // Collect child lines
  const childLines: string[] = [];
  let textContent: string | undefined;

  for (const fm of sorted) {
    const jsName = findJsName(meta, fm);
    const raw = obj[jsName];

    if (fm.kind === "text") {
      // simpleContent $text field
      if (raw !== undefined && raw !== null) {
        textContent = escapeText(String(raw));
      }
      continue;
    }

    // element field
    if (raw === undefined || raw === null) {
      if (fm.nillable) {
        childLines.push(indentStr(options, depth + 1) + `<${fm.xmlName} xsi:nil="true"/>`);
      }
      continue;
    }

    if (fm.isArray && Array.isArray(raw)) {
      for (const item of raw) {
        serializeField(item, fm, options, childLines, depth + 1);
      }
    } else {
      serializeField(raw, fm, options, childLines, depth + 1);
    }
  }

  const pfx = indentStr(options, depth);

  if (textContent !== undefined && childLines.length === 0) {
    // simpleContent: <Tag attr="...">text</Tag>
    out.push(`${pfx}<${elementName}${attrStr}>${textContent}</${elementName}>`);
  } else if (childLines.length === 0) {
    out.push(`${pfx}<${elementName}${attrStr}/>`);
  } else {
    out.push(`${pfx}<${elementName}${attrStr}>`);
    for (const line of childLines) out.push(line);
    out.push(`${pfx}</${elementName}>`);
  }
}

function serializeField(
  value: unknown,
  fm: XmlFieldMeta,
  options: XmlSerializeOptions,
  out: string[],
  depth: number
): void {
  if (value === null || value === undefined) return;

  if (typeof value === "object" && !Array.isArray(value)) {
    if (fm.nestedMeta) {
      serializeObject(value, fm.nestedMeta, fm.xmlName, options, out, depth);
    }
    // Object with no nestedMeta: emit a self-closing tag rather than [object Object]
    return;
  }

  // Primitive value
  const pfx = indentStr(options, depth);
  out.push(`${pfx}<${fm.xmlName}>${escapeText(String(value))}</${fm.xmlName}>`);
}

// ---------------------------------------------------------------------------
// Lookup helpers
// ---------------------------------------------------------------------------

/** Find the JS property name for a field meta by scanning the fields map. */
function findJsName(meta: XmlTypeMeta, target: XmlFieldMeta): string {
  for (const [jsName, fm] of Object.entries(meta.fields)) {
    if (fm === target) return jsName;
  }
  return target.xmlName; // fallback
}

// ---------------------------------------------------------------------------
// String helpers
// ---------------------------------------------------------------------------

function indentStr(options: XmlSerializeOptions, depth: number): string {
  return options.indent ? options.indent.repeat(depth) : "";
}

function escapeText(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeAttr(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
